[package]
name = "financial_data_fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = { version = "2", features = ["json"] }
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
serde_json = "1.0.140"
